services:
  mosquitto:
    image: eclipse-mosquitto:2.0.21
    ports:
      - "1883:1883"
    volumes:
      - ./config:/mosquitto/config
      - ./mosquitto_data:/mosquitto/data
    restart: unless-stopped
    networks:
      - mqtt-network

networks:
  mqtt-network:
    driver: bridge
